// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALxH6vMAMrzadOE-YmVRY_Su9Q3S-UcQQ',
    appId: '1:630029205799:web:8c3a54665b2bf0f02a2902',
    messagingSenderId: '630029205799',
    projectId: 'sholic064',
    authDomain: 'sholic064.firebaseapp.com',
    storageBucket: 'sholic064.firebasestorage.app',
    measurementId: 'G-SF73PD781L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmFHvcRS5Mh0eZiOdZjWluQ2g-pCi-StQ',
    appId: '1:630029205799:android:241e4dc25cf6e75f2a2902',
    messagingSenderId: '630029205799',
    projectId: 'sholic064',
    storageBucket: 'sholic064.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAon_SnnCY0Pc8RDJEyBxVi0ObNLL49qJY',
    appId: '1:630029205799:ios:72eee0e8872004032a2902',
    messagingSenderId: '630029205799',
    projectId: 'sholic064',
    storageBucket: 'sholic064.firebasestorage.app',
    iosBundleId: 'com.example.sholicApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAon_SnnCY0Pc8RDJEyBxVi0ObNLL49qJY',
    appId: '1:630029205799:ios:72eee0e8872004032a2902',
    messagingSenderId: '630029205799',
    projectId: 'sholic064',
    storageBucket: 'sholic064.firebasestorage.app',
    iosBundleId: 'com.example.sholicApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyALxH6vMAMrzadOE-YmVRY_Su9Q3S-UcQQ',
    appId: '1:630029205799:web:489ab4a8e85dade42a2902',
    messagingSenderId: '630029205799',
    projectId: 'sholic064',
    authDomain: 'sholic064.firebaseapp.com',
    storageBucket: 'sholic064.firebasestorage.app',
    measurementId: 'G-S12NRMYENT',
  );
}
